name: Deploy

on:
  push:
      branches:
      - master

jobs: 
  deploy_lambda:
    runs-on: ubuntu-latest
    steps: 
    # - name: Checkout
      - uses: actions/checkout@v2
    # - name: Setup
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install
       env: 
        CI: true
        run: | 
          npm ci
